const RouteNames = {
  HOME: "/home",
  EVENTS: "/events",
  LOGIN: "/login",
  REGISTER: "/register",
  GOOGLE: "/login-google",
  NOT_FOUND: "/not-found",
  DASHBOARD: "/admin/dashboard",
  PRODUCTS: "/products",
  BRANDS:"/brands",
  BRAND_DETAIL:"/brand/:id",
  PRODUCT_DETAIL: "/product/:id",
  SPECIAL_CARE: "/special-care",
  BEAUTY_BLOG: "/beauty-blog",
  SKIN_QUIZ: "/skin-quiz",
  CATEGORIES: "/categories",
  CART: "/cart",
  ACCOUNT: "/account",
  ACCOUNT_ORDERS: "/account/orders",
  ACCOUNT_CHANGE_PASSWORD: "/account/change-password",
  PAYMENT: "/cart/payment/",
  CATEGORIES_MANAGEMENT: "/staff/categories-management",
  BRANDS_MANAGEMENT: "/staff/brands-management",
  SKIN_TYPES_MANAGEMENT: "/staff/skin-types-management",
  PRODUCTS_MANAGEMENT: "/staff/products-management",
  PRODUCT_ADDITION: "/staff/product-addition",
  PRODUCT_VIEW:"/staff/product-update/:id",
  BILLING: "/admin/billing",
  ADMIN_HOME: "/admin/dashboard",
  ADMIN_PROFILE: "/admin/profile",
  ADMIN_RTL: "/admin/rtl",
  ADMIN_SIGNIN: "/admin/sign-in",
  ADMIN_SIGNUP: "/admin/sign-up",
  ADMIN_TABLES: "/admin/tables",
};

export default RouteNames;
