const RouteNames = {
  HOME: "/home",
  EVENTS: "/events",
  LOGIN: "/login",
  REGISTER: "/register",
  GOOGLE: "/login-google",
  NOT_FOUND: "/not-found",
  DASHBOARD: "/admin/dashboard",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: "/product/:id",
  SPECIAL_CARE: "/special-care",
  BRANDS: "/brands",
  BEAUTY_BLOG: "/beauty-blog",
  SKIN_QUIZ: "/skin-quiz",
  CATEGORIES: "/categories",
  CART: "/cart",
  ACCOUNT: "/account",
  ACCOUNT_ORDERS: "/account/orders",
  ACCOUNT_CHANGE_PASSWORD: "/account/change-password",
  PAYMENT: "/cart/payment/",
  CATEGORIES_MANAGEMENT: "/staff/categories-management",
  BRANDS_MANAGEMENT: "/staff/brands-management",
  SKIN_TYPES_MANAGEMENT: "/staff/skin-types-management",
};

export default RouteNames;
